### ISSUE TITLE
TypeError: cannot unpack non-iterable numpy.float32 object

### ISSUE THREAD

**Issue by JuliaSzulc** [suhren/camscan#1]
Keep getting this error when pointing my camera on anything (I guess this is when line detection algorithm is triggered)
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1948, in __call__
  File "tkinter\__init__.py", line 861, in callit
  File "app\app.py", line 477, in show_frame
  File "app\app.py", line 459, in capture
  File "camscan\scanner.py", line 488, in main
  File "camscan\scanner.py", line 58, in draw_hough_lines
TypeError: cannot unpack non-iterable numpy.float32 object
```

**Comment by suhren** [comment]
Thanks for pointing out! This is fixed in the following commit:
https://github.com/suhren/camscan/commit/ec55beb645966a28b20eab443e60e3c74b55e9d6
